src/Entity/Offres.php
<?php

namespace App\Entity;

use App\Repository\OffresRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OffresRepository::class)]
class Offres
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $nbr_chambres = null;

    #[ORM\ManyToOne(inversedBy: 'offres')]
    private ?Etablissement $etablissement = null;

    #[ORM\ManyToOne(inversedBy: 'offres')]
    private ?TypeDeChambre $type_chambres = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbrChambres(): ?int
    {
        return $this->nbr_chambres;
    }

    public function setNbrChambres(int $nbr_chambres): self
    {
        $this->nbr_chambres = $nbr_chambres;

        return $this;
    }

    public function getEtablissement(): ?Etablissement
    {
        return $this->etablissement;
    }

    public function setEtablissement(?Etablissement $etablissement): self
    {
        $this->etablissement = $etablissement;

        return $this;
    }

    public function getTypeChambres(): ?TypeDeChambre
    {
        return $this->type_chambres;
    }

    public function setTypeChambres(?TypeDeChambre $type_chambres): self
    {
        $this->type_chambres = $type_chambres;

        return $this;
    }

    /*
    #[Route('/offretype', name: 'app_typeoffresgroupes ', methods: ['GET'])]
    public function findAllNombreoffreGroupe(OffreRepository $typeChambreRepository): Response
    {
        return $this->render('offre/offretype.html.twig', [
        'offretypechambre' => $typeChambreRepository->findAllNombreoffreGroupe(),]);
    }
    */
}

src/Form/OffresType.php
<?php

namespace App\Form;

use App\Entity\Offres;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OffresType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nbr_chambres')
            ->add('etablissement')
            ->add('type_chambres')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Offres::class,
        ]);
    }
}

src/Controller/OffresController.php
<?php

namespace App\Controller;

use App\Entity\Offres;
use App\Form\OffresType;
use App\Repository\OffresRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

#[Route('/offres')]
class OffresController extends AbstractController
{
    #[Route('/', name: 'app_offres_index', methods: ['GET'])]
    public function index(OffresRepository $offresRepository): Response
    {
        return $this->render('offres/index.html.twig', [
            'offres' => $offresRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_offres_new', methods: ['GET', 'POST'])]
    public function new(Request $request, OffresRepository $offresRepository): Response
    {
        $offre = new Offres();
        $form = $this->createForm(OffresType::class, $offre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $offresRepository->save($offre, true);

            return $this->redirectToRoute('app_offres_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('offres/new.html.twig', [
            'offre' => $offre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_offres_show', methods: ['GET'])]
    public function show(Offres $offre): Response
    {
        return $this->render('offres/show.html.twig', [
            'offre' => $offre,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_offres_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Offres $offre, OffresRepository $offresRepository): Response
    {
        $form = $this->createForm(OffresType::class, $offre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $offresRepository->save($offre, true);

            return $this->redirectToRoute('app_offres_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('offres/edit.html.twig', [
            'offre' => $offre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_offres_delete', methods: ['POST'])]
    public function delete(Request $request, Offres $offre, OffresRepository $offresRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$offre->getId(), $request->request->get('_token'))) {
            $offresRepository->remove($offre, true);
        }

        return $this->redirectToRoute('app_offres_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/offres/_delete_form.html.twig
<form method="post" action="{{ path('app_offres_delete', {'id': offre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ offre.id) }}">
    <button class="btn">Delete</button>
</form>

templates/offres/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/offres/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Offres{% endblock %}

{% block body %}
    <h1>Edit Offres</h1>

    {{ include('offres/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_offres_index') }}">back to list</a>

    {{ include('offres/_delete_form.html.twig') }}
{% endblock %}

templates/offres/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Offres index{% endblock %}

{% block body %}
    <h1>Offres index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nbr_chambres</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for offre in offres %}
            <tr>
                <td>{{ offre.id }}</td>
                <td>{{ offre.nbrChambres }}</td>
                <td>
                    <a href="{{ path('app_offres_show', {'id': offre.id}) }}">show</a>
                    <a href="{{ path('app_offres_edit', {'id': offre.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_offres_new') }}">Create new</a>
{% endblock %}

templates/offres/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Offres{% endblock %}

{% block body %}
    <h1>Create new Offres</h1>

    {{ include('offres/_form.html.twig') }}

    <a href="{{ path('app_offres_index') }}">back to list</a>
{% endblock %}

templates/offres/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Offres{% endblock %}

{% block body %}
    <h1>Offres</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ offre.id }}</td>
            </tr>
            <tr>
                <th>Nbr_chambres</th>
                <td>{{ offre.nbrChambres }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_offres_index') }}">back to list</a>

    <a href="{{ path('app_offres_edit', {'id': offre.id}) }}">edit</a>

    {{ include('offres/_delete_form.html.twig') }}
{% endblock %}